name: Update README

on:
  schedule:
    # Runs at 12 AM UTC every day
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" "https://github-readme-stats.vercel.app/api?username=benami171&count_private=true&theme=codeSTACKr&show_icons=true" -o stats.svg
          curl -H "Authorization: token $GH_TOKEN" "https://github-readme-streak-stats.herokuapp.com?user=benami171&count_private=true&theme=highcontrast&date_format=j%20M%5B%20Y%5D" -o streak.svg

          sed -i 's|https://github-readme-stats.vercel.app/api?username=benami171&theme=codeSTACKr&show_icons=true|./stats.svg|' README.md
          sed -i 's|https://github-readme-streak-stats.herokuapp.com?user=benami171&theme=highcontrast&date_format=j%20M%5B%20Y%5D|./streak.svg|' README.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md stats.svg streak.svg
          git commit -m "Update README with latest stats"
          git push
